@startmindmap
* Führung

'GRUNDLAGEN

** Grundlagen
*** Was ist Führung? => Prozess der Beeinflussung und Lenkung
**** Begriffe
*** Warum braucht es Führung?
*** Wer führt?
*** Wie wird geführt?

'AUFGABEN UND INSTRUMENTE

** Aufgaben und Instrumente von Führung
*** Wirkoungsmodell der Führung
*** Organisation
*** Budgets
*** Anreizsysteme
*** Arbeitstechniken (Berichte, Gespräche...)

'ATKUELLES

** Aktuelle Sonderthemen der Führung
*** Innovationsmanagement
*** Diversity Managment
*** Unternehmensethik
@endmindmap